export const DEALS = {
  GET: "GET_DEALS",
};

export const PRODUCTS = {
  GET: "GET_PRODUCTS",
};

export const CART = {
  ADD: "ADD_TO_CART",
  REMOVE: "REMOVE_FROM_CART",
  EMPTY: "EMPTY_CART",
  ADD_QUANTITY: "ADD_QUANTITY",
  SUB_QUANTITY: "SUB_QUANTITY",
};

export const COUPONS = {
  GET: "GET_COUPONS",
  APPLY: "APPLY_COUPON",
  APPLIED_COUNT: "APPLIED_COUNT",
  INCREMENT_ORDER_COUNT: "INCREMENT_ORDER_COUNT",
};
